# Generated by Django 5.2.5 on 2025-08-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('stars', models.CharField(choices=[(3, 'Normal'), (4, 'Good'), (5, 'Prefect'), (1, 'Very Bad'), (2, 'Bad')], max_length=5)),
            ],
        ),
    ]
