# Generated by Django 5.2.5 on 2025-08-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_picture_alter_room_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='datetime_modifide',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
