# Generated by Django 5.2.5 on 2025-08-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_datetime_created_room_datetime_modifide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='datetime_modifide',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
