# Generated by Django 5.2.5 on 2025-08-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='stars',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=1),
        ),
    ]
