# Generated by Django 5.2.5 on 2025-09-01 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_room_author_imagemulti'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemulti',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='rooms.room'),
        ),
    ]
