# Generated by Django 5.2.5 on 2025-09-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_imagemulti_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemulti',
            name='images',
            field=models.ImageField(blank=True, upload_to='rooms.models.upload_to_path'),
        ),
    ]
