# Generated by Django 5.2.5 on 2025-09-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_alter_imagemulti_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemulti',
            name='images',
            field=models.ImageField(blank=True, upload_to='covers/images/'),
        ),
    ]
