# Generated by Django 5.2.5 on 2025-09-01 07:30

import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_imagemulti_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemulti',
            name='images',
            field=models.ImageField(blank=True, upload_to=rooms.models.upload_to_path),
        ),
    ]
